--[ What is ZareX? ]--
-- ZareX is a Roblox Script Executor.
--[ What type of Script Executor is it? ]--
-- Its a Server Side GUI. (Soon it will be Local Side)
--[ Is ZareX free to use? ]--
-- Yes, ZareX IS free. Soon there will be a premium version but there will still be a free version separately.
--[ Can I execute malicious code in ZareX? ]--
-- No, its against Roblox TOS. If your going to use malicious code it better be for good. But still, I cant really do anything about it.
--[ What version is ZareX currently in? ]--
-- ZareX is currently in the v0.9
